<?php

namespace CIELO\Constants;

/**
 * Class OpcaoExtrato
 * @package CIELO\Constants
 */
class OpcaoExtrato
{
    const CIELO_OPCAO_EXTRATO_VENDA_COM_CV = '01';
    const CIELO_OPCAO_EXTRATO_VENDA_SEM_CV = '02';
    const CIELO_OPCAO_EXTRATO_VENDA_COM_CV_PARC_FUTURO = '03';
    const CIELO_OPCAO_EXTRATO_PAGAMENTO_COM_CV = '04';
    const CIELO_OPCAO_EXTRATO_PAGAMENTO_SEM_CV = '05';
    const CIELO_OPCAO_EXTRATO_ANTECIPACAO_RECEBIVEIS = '06';
    const CIELO_OPCAO_EXTRATO_CESSAO_RECEBIVEIS = '07';
    const CIELO_OPCAO_EXTRATO_PARCELAS_PENDENTES = '08';
    const CIELO_OPCAO_EXTRATO_SALDO_ABERTO = '09';
}