dist: trusty
sudo: required

language: php
php:
  - '5.6'

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
  - cp config.ini.dist config.ini
  - cp config.xml.dist config.xml
  - mysql -u root -e 'create database edi;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost'"
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer install
  - composer --version
  - composer install --no-dev --verbose

script:
  - vendor/bin/doctrine orm:schema-tool:update --force
  - "phpunit --configuration phpunit.xml --coverage-text"